import { CreatAdvertisementDto } from "src/advertisements/dtos/create-advertisements.dto";
import { CreateApplicantJobstDto } from "src/applicants-job/dtos/create-applicants-job";
import { PatchApplicantJobsDto } from "src/applicants-job/dtos/patch-applicants-job.dto";
import { CreateBannerDto } from "src/banner/dtos/create-banner.dto";
import { PatchBannerDto } from "src/banner/dtos/patch-banner.dto";
import { CreateBlogsDto } from "src/blogs/dto/create-blogs-blogs.dto";
import { PatchBlogDto } from "src/blogs/dto/patch-blog.dto";
import { CreateCategoryDto } from "src/categories/dto/create-category.dto";
import { PatchCategoryDto } from "src/categories/dto/patch-category.dto";
import { CreateConsultancyDto } from "src/consultancy/dtos/create-consultancy.dto";
import { PatchConsultancyDto } from "src/consultancy/dtos/patch-consultancy.dto";
import { CreateEducationsDto } from "src/educations/dtos/create-educations.dto";
import { PatchEducationDto } from "src/educations/dtos/patch-education.dto";
import { CreateGallarysDto } from "src/gallary/dtos/create-gallary.dto";
import { PatchGallaryDto } from "src/gallary/dtos/patch-gallary.dto";
import { CreateGraduatestDto } from "src/graduates/dtos/create-graduates";
import { PatchGraduatesDto } from "src/graduates/dtos/patch-graduates.dto";
import { CreateHeroSliderDto } from "src/hero-sliders/dtos/create-hero-slider.dto";
import { PatchPostDto } from "src/hero-sliders/dtos/patch-consultancy.dto";
import { CreateJobDto } from "src/jobs/dtos/create-job.dto";
import { PatchJobDto } from "src/jobs/dtos/patch-job.dto";
import { CreateMagazineDto } from "src/magazines/dto/create-magazine.dto";
import { PatchMagazineDto } from "src/magazines/dto/patch-magazine.dto";
import { CreatePartnersDto } from "src/partners/dtos/create-partners.dto";
import { PatchPartnerDto } from "src/partners/dtos/patch-partners.dto";
import { CreatePatchDto } from "src/patch/dtos/create-patch.dto";
import { PatchPatchDto } from "src/patch/dtos/patch-patch.dto";
import { PatchServiceDto } from "src/services-home/dto/patch-service.dto";
import { CreateServiceDto } from "src/services-home/dto/service.dto";
import { CreateSettingDto } from "src/settings/dtos/create-setting.dto";
import { patchSettingDto } from "src/settings/dtos/patch-setting.dto";
import { CreateSocialLinkDto } from "src/social-links/dtos/create-social-link";
import { PatchSocialLinkDto } from "src/social-links/dtos/patch-social-link.dto";
import { CreateStatisticsDto } from "src/statistics/dtos/create-statistics.dto";
import { PatchStatisticsDto } from "src/statistics/dtos/patch-statistics.dto";
import { CreateTeamDto } from "src/team/dtos/create-team.dto";
import { PatchTeamDto } from "src/team/dtos/patch-team.dto";
export declare const dtoMappings: {
    "/api/v1/consultancy/store": typeof CreateConsultancyDto;
    "/api/v1/consultancy/update": typeof PatchConsultancyDto;
    "/api/v1/education/store": typeof CreateEducationsDto;
    "/api/v1/education/update": typeof PatchEducationDto;
    "/api/v1/team/store": typeof CreateTeamDto;
    "/api/v1/team/update": typeof PatchTeamDto;
    "/api/v1/partner/store": typeof CreatePartnersDto;
    "/api/v1/partner/update": typeof PatchPartnerDto;
    "/api/v1/slider/store": typeof CreateHeroSliderDto;
    "/api/v1/slider/update": typeof PatchPostDto;
    "/api/v1/banner/store": typeof CreateBannerDto;
    "/api/v1/banner/update": typeof PatchBannerDto;
    "/api/v1/statistics/store": typeof CreateStatisticsDto;
    "/api/v1/statistics/update": typeof PatchStatisticsDto;
    "/api/v1/gallary/store": typeof CreateGallarysDto;
    "/api/v1/gallary/update": typeof PatchGallaryDto;
    "/api/v1/category/store": typeof CreateCategoryDto;
    "/api/v1/category/update": typeof PatchCategoryDto;
    "/api/v1/job/store": typeof CreateJobDto;
    "/api/v1/job/update": typeof PatchJobDto;
    "/api/v1/job/store/front": typeof CreateJobDto;
    "/api/v1/magazine/store": typeof CreateMagazineDto;
    "/api/v1/magazine/update": typeof PatchMagazineDto;
    "/api/v1/graduates/store": typeof CreateGraduatestDto;
    "/api/v1/graduates/update": typeof PatchGraduatesDto;
    "/api/v1/graduates/store/front": typeof CreateGraduatestDto;
    "/api/v1/graduates/update/front": typeof PatchGraduatesDto;
    "/api/v1/blog/store": typeof CreateBlogsDto;
    "/api/v1/blog/update": typeof PatchBlogDto;
    "/api/v1/setting/store": typeof CreateSettingDto;
    "/api/v1/setting/update": typeof patchSettingDto;
    "/api/v1/patch/store": typeof CreatePatchDto;
    "/api/v1/patch/update": typeof PatchPatchDto;
    "/api/v1/service-home/store": typeof CreateServiceDto;
    "/api/v1/service-home/update": typeof PatchServiceDto;
    "/api/v1/social-link/store": typeof CreateSocialLinkDto;
    "/api/v1/social-link/update": typeof PatchSocialLinkDto;
    "/api/v1/applicant-Job/store/front": typeof CreateApplicantJobstDto;
    "/api/v1/applicant-Job/update/front": typeof PatchApplicantJobsDto;
    "/api/v1/advertisement/store": typeof CreatAdvertisementDto;
    "/api/v1/advertisement/update": typeof CreatAdvertisementDto;
};
